# Generated by Django 4.1.3 on 2022-12-28 14:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box_office',
            fields=[
                ('window_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('window_name', models.CharField(max_length=30, unique=True)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('ticket_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_organizer',
            fields=[
                ('organizer_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('adres', models.CharField(max_length=100, unique=True)),
                ('number_of_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(max_length=50, unique=True)),
                ('rating', models.PositiveIntegerField(unique=True)),
                ('coach_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.coach')),
                ('stadium_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('organizer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='master.event_organizer')),
                ('prize_fund', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('expenses', models.PositiveIntegerField(null=True)),
                ('profit', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_manager',
            fields=[
                ('manager_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('team_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.team')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateField()),
                ('salary', models.PositiveIntegerField()),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.team_manager')),
                ('organizer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.event_organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match_history',
            fields=[
                ('match_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('team_score', models.PositiveIntegerField()),
                ('match_date', models.DateField()),
                ('stadium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.stadium')),
                ('team_id', models.ManyToManyField(to='master.team')),
            ],
        ),
        migrations.AddField(
            model_name='event_organizer',
            name='stadium_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.stadium'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('organizer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.event_organizer')),
                ('window_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.box_office')),
            ],
        ),
        migrations.AddField(
            model_name='box_office',
            name='stadium_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.stadium'),
        ),
    ]
