# Generated by Django 4.1.3 on 2022-12-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_box_office_event_organizer_stadium_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='number',
            new_name='number_of_seats',
        ),
    ]
